name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node LTS
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Set up package manager
        run: corepack enable pnpm

      - name: Build & Test
        run: |
          pnpm install 
          pnpm build
          pnpm test
