name: Publish to NPM

on:
  release:
    types: [released, prereleased]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - name: Set up package manager
        run: corepack enable

      - run: |
          pnpm install --frozen-lockfile
          pnpm build
          pnpm test
          pnpm publish --access public --no-git-checks

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
